# Generated by Django 3.1.1 on 2020-10-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
